[2025-03-24T22:19:09.154+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:19:09.230+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T22:19:09.256+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T22:19:09.258+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:19:09.401+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app1> on 2024-03-08 00:00:00+00:00
[2025-03-24T22:19:09.435+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp8qx83j4o']
[2025-03-24T22:19:09.439+0000] {standard_task_runner.py:105} INFO - Job 118: Subtask php_app1
[2025-03-24T22:19:09.449+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4850) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:19:09.456+0000] {standard_task_runner.py:72} INFO - Started process 4865 to run task
[2025-03-24T22:19:09.690+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:19:10.015+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andreeppinghaus' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-24T22:19:10.023+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:19:10.106+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:19:10.107+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sudo docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app1']
[2025-03-24T22:19:10.147+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:19:10.286+0000] {subprocess.py:106} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2025-03-24T22:19:10.287+0000] {subprocess.py:106} INFO - sudo: a password is required
[2025-03-24T22:19:10.287+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-24T22:19:10.337+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:19:10.440+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250324T221909, end_date=20250324T221910
[2025-03-24T22:19:10.701+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:19:10.707+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 118 for task php_app1 (Bash command failed. The command returned a non-zero exit code 1.; 4865)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:19:10.754+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:19:10.899+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T22:19:10.922+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T22:24:18.951+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:24:19.213+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T22:24:19.238+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T22:24:19.239+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:24:19.633+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app1> on 2024-03-08 00:00:00+00:00
[2025-03-24T22:24:19.724+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5269) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:24:19.744+0000] {standard_task_runner.py:72} INFO - Started process 5296 to run task
[2025-03-24T22:24:19.733+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpgn4q7dcu']
[2025-03-24T22:24:19.759+0000] {standard_task_runner.py:105} INFO - Job 157: Subtask php_app1
[2025-03-24T22:24:19.985+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:24:20.785+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-24T22:24:20.786+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:24:20.867+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:24:20.868+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sudo docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app1']
[2025-03-24T22:24:20.903+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:24:21.009+0000] {subprocess.py:106} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2025-03-24T22:24:21.011+0000] {subprocess.py:106} INFO - sudo: a password is required
[2025-03-24T22:24:21.013+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-24T22:24:21.036+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:24:21.053+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250324T222419, end_date=20250324T222421
[2025-03-24T22:24:21.254+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:24:21.267+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 157 for task php_app1 (Bash command failed. The command returned a non-zero exit code 1.; 5296)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:24:21.351+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:24:21.439+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T22:27:26.693+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:27:26.802+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T22:27:26.895+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T22:27:26.896+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:27:27.020+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app1> on 2024-03-08 00:00:00+00:00
[2025-03-24T22:27:27.049+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5709) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:27:27.050+0000] {standard_task_runner.py:72} INFO - Started process 5744 to run task
[2025-03-24T22:27:27.046+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpj6u_n_rs']
[2025-03-24T22:27:27.053+0000] {standard_task_runner.py:105} INFO - Job 189: Subtask php_app1
[2025-03-24T22:27:27.557+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:27:28.844+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-24T22:27:28.845+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:27:29.197+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:27:29.210+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app1']
[2025-03-24T22:27:29.326+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:27:29.608+0000] {subprocess.py:106} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2025-03-24T22:27:29.609+0000] {subprocess.py:106} INFO - See 'docker run --help'.
[2025-03-24T22:27:29.620+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2025-03-24T22:27:29.891+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T22:27:30.015+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250324T222726, end_date=20250324T222730
[2025-03-24T22:27:30.772+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:27:30.780+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 189 for task php_app1 (Bash command failed. The command returned a non-zero exit code 125.; 5744)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T22:27:30.848+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:27:31.247+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T22:27:31.267+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T23:57:27.705+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T23:57:27.747+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T23:57:27.853+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T23:57:27.854+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T23:57:28.131+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app1> on 2024-03-08 00:00:00+00:00
[2025-03-24T23:57:28.182+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=310) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T23:57:28.184+0000] {standard_task_runner.py:72} INFO - Started process 383 to run task
[2025-03-24T23:57:28.176+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp2ge9j_v4']
[2025-03-24T23:57:28.189+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask php_app1
[2025-03-24T23:57:28.364+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [running]> on host 8e89fdaa3360
[2025-03-24T23:57:28.699+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-24T23:57:28.703+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T23:57:28.735+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T23:57:28.737+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app1']
[2025-03-24T23:57:28.756+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T23:57:28.797+0000] {subprocess.py:106} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2025-03-24T23:57:28.798+0000] {subprocess.py:106} INFO - See 'docker run --help'.
[2025-03-24T23:57:28.801+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2025-03-24T23:57:28.818+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T23:57:28.834+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250324T235727, end_date=20250324T235728
[2025-03-24T23:57:28.904+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T23:57:28.905+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task php_app1 (Bash command failed. The command returned a non-zero exit code 125.; 383)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T23:57:28.939+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T23:57:28.974+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T23:57:28.979+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T00:18:36.653+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T00:18:36.774+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-25T00:18:36.857+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-25T00:18:36.859+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T00:18:36.973+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-08 00:00:00+00:00
[2025-03-25T00:18:37.014+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=431) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T00:18:37.015+0000] {standard_task_runner.py:72} INFO - Started process 437 to run task
[2025-03-25T00:18:37.006+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpotx6qb9b']
[2025-03-25T00:18:37.026+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask php_app1
[2025-03-25T00:18:37.461+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [running]> on host 0f77abd8a5ce
[2025-03-25T00:18:38.244+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-25T00:18:38.245+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T00:18:38.729+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T00:18:38.752+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:18:38.770+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250325T001836, end_date=20250325T001838
[2025-03-25T00:18:39.263+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T00:18:39.277+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task php_app1 (Failed to establish connection to any given Docker hosts.; 437)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:18:39.376+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T00:18:39.407+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T00:25:43.961+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T00:25:44.095+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-25T00:25:44.172+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-25T00:25:44.173+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T00:25:44.311+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-08 00:00:00+00:00
[2025-03-25T00:25:44.375+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp4nw31ujt']
[2025-03-25T00:25:44.409+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask php_app1
[2025-03-25T00:25:44.439+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=233) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T00:25:44.441+0000] {standard_task_runner.py:72} INFO - Started process 252 to run task
[2025-03-25T00:25:44.948+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [running]> on host 7e2e363232cf
[2025-03-25T00:25:45.671+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-25T00:25:45.672+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T00:25:45.776+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T00:25:45.805+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:25:45.883+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250325T002544, end_date=20250325T002545
[2025-03-25T00:25:46.259+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T00:25:46.260+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task php_app1 (Failed to establish connection to any given Docker hosts.; 252)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:25:46.377+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T00:25:46.510+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T00:25:46.522+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T12:45:32.985+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T12:45:33.090+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-25T12:45:33.114+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-25T12:45:33.118+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T12:45:33.461+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-08 00:00:00+00:00
[2025-03-25T12:45:33.537+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=249) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T12:45:33.539+0000] {standard_task_runner.py:72} INFO - Started process 263 to run task
[2025-03-25T12:45:33.544+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpsp3fdmsr']
[2025-03-25T12:45:33.547+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask php_app1
[2025-03-25T12:45:33.843+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [running]> on host c83c0958fca4
[2025-03-25T12:45:34.664+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-25T12:45:34.667+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T12:45:34.925+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T12:45:34.977+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T12:45:35.040+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250325T124533, end_date=20250325T124535
[2025-03-25T12:45:35.192+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T12:45:35.192+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task php_app1 (Failed to establish connection to any given Docker hosts.; 263)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T12:45:35.309+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T12:45:35.446+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T12:45:35.453+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T11:52:50.324+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T11:52:50.445+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-26T11:52:50.468+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-26T11:52:50.468+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T11:52:50.538+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-08 00:00:00+00:00
[2025-03-26T11:52:50.581+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpzw_b1q7i']
[2025-03-26T11:52:50.585+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask php_app1
[2025-03-26T11:52:50.586+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=243) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T11:52:50.588+0000] {standard_task_runner.py:72} INFO - Started process 268 to run task
[2025-03-26T11:52:50.834+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [running]> on host c0a4d7e9da1a
[2025-03-26T11:52:51.243+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-26T11:52:51.249+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T11:52:51.296+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-26T11:52:51.318+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T11:52:51.342+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250326T115250, end_date=20250326T115251
[2025-03-26T11:52:51.434+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T11:52:51.434+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task php_app1 (Failed to establish connection to any given Docker hosts.; 268)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T11:52:51.500+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-26T11:52:51.578+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T11:52:51.592+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T13:18:10.044+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T13:18:10.133+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-26T13:18:10.172+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-26T13:18:10.176+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T13:18:10.275+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-08 00:00:00+00:00
[2025-03-26T13:18:10.299+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1269) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T13:18:10.301+0000] {standard_task_runner.py:72} INFO - Started process 1283 to run task
[2025-03-26T13:18:10.294+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp1vxbvfuf']
[2025-03-26T13:18:10.303+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask php_app1
[2025-03-26T13:18:10.471+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [running]> on host f731374053d7
[2025-03-26T13:18:10.684+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-26T13:18:10.685+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T13:18:10.720+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[2025-03-26T13:18:10.734+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T13:18:10.747+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250326T131810, end_date=20250326T131810
[2025-03-26T13:18:10.796+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T13:18:10.796+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task php_app1 (Failed to establish connection to any given Docker hosts.; 1283)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T13:18:10.814+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-26T13:18:10.843+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T13:18:10.847+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T13:38:24.870+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T13:38:25.049+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-26T13:38:25.078+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-26T13:38:25.079+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T13:38:25.294+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-08 00:00:00+00:00
[2025-03-26T13:38:25.408+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=278) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T13:38:25.411+0000] {standard_task_runner.py:72} INFO - Started process 297 to run task
[2025-03-26T13:38:25.433+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpw2xs0gb_']
[2025-03-26T13:38:25.492+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask php_app1
[2025-03-26T13:38:26.224+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-08T00:00:00+00:00 [running]> on host 3d581a580455
[2025-03-26T13:38:27.051+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-26T13:38:27.058+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T13:38:27.349+0000] {docker.py:345} INFO - Starting docker container from image php-app1
[2025-03-26T13:38:27.390+0000] {docker.py:353} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-03-26T13:38:31.217+0000] {docker.py:69} INFO - array(20) {
[2025-03-26T13:38:31.219+0000] {docker.py:69} INFO -   [0]=>
[2025-03-26T13:38:31.219+0000] {docker.py:69} INFO -   object(stdClass)#2 (3) {
[2025-03-26T13:38:31.219+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.220+0000] {docker.py:69} INFO -     int(0)
[2025-03-26T13:38:31.220+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.221+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.221+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.221+0000] {docker.py:69} INFO -     int(1742852307)
[2025-03-26T13:38:31.221+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.222+0000] {docker.py:69} INFO -   [1]=>
[2025-03-26T13:38:31.222+0000] {docker.py:69} INFO -   object(stdClass)#3 (3) {
[2025-03-26T13:38:31.222+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.223+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.224+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.225+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.225+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.225+0000] {docker.py:69} INFO -     int(1742852309)
[2025-03-26T13:38:31.226+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.226+0000] {docker.py:69} INFO -   [2]=>
[2025-03-26T13:38:31.226+0000] {docker.py:69} INFO -   object(stdClass)#4 (3) {
[2025-03-26T13:38:31.227+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.227+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.227+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.228+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.229+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.229+0000] {docker.py:69} INFO -     int(1742852311)
[2025-03-26T13:38:31.230+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.232+0000] {docker.py:69} INFO -   [3]=>
[2025-03-26T13:38:31.233+0000] {docker.py:69} INFO -   object(stdClass)#5 (3) {
[2025-03-26T13:38:31.234+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.234+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.235+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.235+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.236+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.236+0000] {docker.py:69} INFO -     int(1742852314)
[2025-03-26T13:38:31.237+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.237+0000] {docker.py:69} INFO -   [4]=>
[2025-03-26T13:38:31.241+0000] {docker.py:69} INFO -   object(stdClass)#6 (3) {
[2025-03-26T13:38:31.242+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.243+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.243+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.244+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.249+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.250+0000] {docker.py:69} INFO -     int(1742996301)
[2025-03-26T13:38:31.250+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.251+0000] {docker.py:69} INFO -   [5]=>
[2025-03-26T13:38:31.251+0000] {docker.py:69} INFO -   object(stdClass)#7 (3) {
[2025-03-26T13:38:31.251+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.252+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.253+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.254+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.255+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.255+0000] {docker.py:69} INFO -     int(1742996302)
[2025-03-26T13:38:31.256+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.257+0000] {docker.py:69} INFO -   [6]=>
[2025-03-26T13:38:31.257+0000] {docker.py:69} INFO -   object(stdClass)#8 (3) {
[2025-03-26T13:38:31.257+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.258+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.258+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.263+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.264+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.265+0000] {docker.py:69} INFO -     int(1742996302)
[2025-03-26T13:38:31.265+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.266+0000] {docker.py:69} INFO -   [7]=>
[2025-03-26T13:38:31.271+0000] {docker.py:69} INFO -   object(stdClass)#9 (3) {
[2025-03-26T13:38:31.272+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.280+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.281+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.282+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.282+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.283+0000] {docker.py:69} INFO -     int(1742996303)
[2025-03-26T13:38:31.283+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.292+0000] {docker.py:69} INFO -   [8]=>
[2025-03-26T13:38:31.293+0000] {docker.py:69} INFO -   object(stdClass)#10 (3) {
[2025-03-26T13:38:31.294+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.297+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.298+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.299+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.303+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.304+0000] {docker.py:69} INFO -     int(1742996304)
[2025-03-26T13:38:31.305+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.307+0000] {docker.py:69} INFO -   [9]=>
[2025-03-26T13:38:31.308+0000] {docker.py:69} INFO -   object(stdClass)#11 (3) {
[2025-03-26T13:38:31.308+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.309+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.309+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.309+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.310+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.310+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:31.311+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.311+0000] {docker.py:69} INFO -   [10]=>
[2025-03-26T13:38:31.312+0000] {docker.py:69} INFO -   object(stdClass)#12 (3) {
[2025-03-26T13:38:31.314+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.315+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.317+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.317+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.318+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.318+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:31.319+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.319+0000] {docker.py:69} INFO -   [11]=>
[2025-03-26T13:38:31.320+0000] {docker.py:69} INFO -   object(stdClass)#13 (3) {
[2025-03-26T13:38:31.320+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.321+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.322+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.322+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.324+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.327+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:31.331+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.336+0000] {docker.py:69} INFO -   [12]=>
[2025-03-26T13:38:31.337+0000] {docker.py:69} INFO -   object(stdClass)#14 (3) {
[2025-03-26T13:38:31.338+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.339+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.339+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.340+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.340+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.347+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:31.349+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.349+0000] {docker.py:69} INFO -   [13]=>
[2025-03-26T13:38:31.350+0000] {docker.py:69} INFO -   object(stdClass)#15 (3) {
[2025-03-26T13:38:31.350+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.351+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.351+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.352+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.352+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.353+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:31.353+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.353+0000] {docker.py:69} INFO -   [14]=>
[2025-03-26T13:38:31.354+0000] {docker.py:69} INFO -   object(stdClass)#16 (3) {
[2025-03-26T13:38:31.354+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.355+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.355+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.359+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.360+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.360+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:31.365+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.366+0000] {docker.py:69} INFO -   [15]=>
[2025-03-26T13:38:31.366+0000] {docker.py:69} INFO -   object(stdClass)#17 (3) {
[2025-03-26T13:38:31.366+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.367+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.367+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.368+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.368+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.368+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:31.369+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.369+0000] {docker.py:69} INFO -   [16]=>
[2025-03-26T13:38:31.370+0000] {docker.py:69} INFO -   object(stdClass)#18 (3) {
[2025-03-26T13:38:31.371+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.371+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.372+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.372+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.373+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.376+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:31.377+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.377+0000] {docker.py:69} INFO -   [17]=>
[2025-03-26T13:38:31.378+0000] {docker.py:69} INFO -   object(stdClass)#19 (3) {
[2025-03-26T13:38:31.378+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.379+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.379+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.380+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.380+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.381+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:31.381+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.382+0000] {docker.py:69} INFO -   [18]=>
[2025-03-26T13:38:31.384+0000] {docker.py:69} INFO -   object(stdClass)#20 (3) {
[2025-03-26T13:38:31.385+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.386+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.386+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.386+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.387+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.387+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:31.388+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.388+0000] {docker.py:69} INFO -   [19]=>
[2025-03-26T13:38:31.388+0000] {docker.py:69} INFO -   array(3) {
[2025-03-26T13:38:31.389+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.389+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.390+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.390+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.390+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.391+0000] {docker.py:69} INFO -     int(1742996311)
[2025-03-26T13:38:31.391+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.392+0000] {docker.py:69} INFO - }
[2025-03-26T13:38:33.413+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T13:38:33.414+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250326T133825, end_date=20250326T133833
[2025-03-26T13:38:33.773+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-26T13:38:33.866+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T13:38:33.886+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
