[2025-03-24T22:19:24.663+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:19:24.731+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T22:19:24.760+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T22:19:24.760+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:19:24.819+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app2> on 2024-03-08 00:00:00+00:00
[2025-03-24T22:19:24.854+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4951) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:19:24.856+0000] {standard_task_runner.py:72} INFO - Started process 4964 to run task
[2025-03-24T22:19:24.948+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpg0_lvbth']
[2025-03-24T22:19:25.030+0000] {standard_task_runner.py:105} INFO - Job 134: Subtask php_app2
[2025-03-24T22:19:25.442+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:19:26.211+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andreeppinghaus' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-24T22:19:26.212+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:19:26.269+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:19:26.271+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sudo docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app2']
[2025-03-24T22:19:26.364+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:19:26.420+0000] {subprocess.py:106} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2025-03-24T22:19:26.422+0000] {subprocess.py:106} INFO - sudo: a password is required
[2025-03-24T22:19:26.424+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-24T22:19:26.503+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:19:26.546+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250324T221924, end_date=20250324T221926
[2025-03-24T22:19:27.376+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:19:27.378+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 134 for task php_app2 (Bash command failed. The command returned a non-zero exit code 1.; 4964)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:19:27.425+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:19:27.667+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T22:19:27.733+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T22:24:19.056+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:24:19.106+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T22:24:19.141+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T22:24:19.142+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:24:19.569+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app2> on 2024-03-08 00:00:00+00:00
[2025-03-24T22:24:19.616+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpyo9dy37z']
[2025-03-24T22:24:19.624+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5268) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:24:19.625+0000] {standard_task_runner.py:72} INFO - Started process 5292 to run task
[2025-03-24T22:24:19.629+0000] {standard_task_runner.py:105} INFO - Job 158: Subtask php_app2
[2025-03-24T22:24:19.991+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:24:20.591+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-24T22:24:20.592+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:24:20.631+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:24:20.632+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sudo docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app2']
[2025-03-24T22:24:20.669+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:24:20.801+0000] {subprocess.py:106} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2025-03-24T22:24:20.803+0000] {subprocess.py:106} INFO - sudo: a password is required
[2025-03-24T22:24:20.804+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-24T22:24:20.894+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:24:21.030+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250324T222419, end_date=20250324T222421
[2025-03-24T22:24:21.528+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:24:21.537+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 158 for task php_app2 (Bash command failed. The command returned a non-zero exit code 1.; 5292)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:24:21.771+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:24:21.838+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T22:24:21.859+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T22:27:27.199+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:27:27.413+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T22:27:27.434+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T22:27:27.435+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:27:27.687+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app2> on 2024-03-08 00:00:00+00:00
[2025-03-24T22:27:27.723+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5707) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:27:27.731+0000] {standard_task_runner.py:72} INFO - Started process 5750 to run task
[2025-03-24T22:27:27.717+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpn5e8fh2e']
[2025-03-24T22:27:27.737+0000] {standard_task_runner.py:105} INFO - Job 191: Subtask php_app2
[2025-03-24T22:27:28.123+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:27:28.676+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-24T22:27:28.690+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:27:28.829+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:27:28.830+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app2']
[2025-03-24T22:27:29.057+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:27:29.176+0000] {subprocess.py:106} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2025-03-24T22:27:29.177+0000] {subprocess.py:106} INFO - See 'docker run --help'.
[2025-03-24T22:27:29.200+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2025-03-24T22:27:29.376+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T22:27:29.610+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250324T222727, end_date=20250324T222729
[2025-03-24T22:27:30.029+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:27:30.040+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 191 for task php_app2 (Bash command failed. The command returned a non-zero exit code 125.; 5750)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T22:27:30.077+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:27:30.646+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T22:27:30.741+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T23:57:28.087+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T23:57:28.201+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T23:57:28.218+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-24T23:57:28.219+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T23:57:28.255+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app2> on 2024-03-08 00:00:00+00:00
[2025-03-24T23:57:28.290+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=317) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T23:57:28.292+0000] {standard_task_runner.py:72} INFO - Started process 389 to run task
[2025-03-24T23:57:28.296+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpqz0rzs__']
[2025-03-24T23:57:28.299+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask php_app2
[2025-03-24T23:57:28.501+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [running]> on host 8e89fdaa3360
[2025-03-24T23:57:28.756+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-24T23:57:28.758+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T23:57:28.796+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T23:57:28.798+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app2']
[2025-03-24T23:57:28.818+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T23:57:28.849+0000] {subprocess.py:106} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2025-03-24T23:57:28.850+0000] {subprocess.py:106} INFO - See 'docker run --help'.
[2025-03-24T23:57:28.854+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2025-03-24T23:57:28.882+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T23:57:28.898+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250324T235728, end_date=20250324T235728
[2025-03-24T23:57:28.948+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T23:57:28.949+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task php_app2 (Bash command failed. The command returned a non-zero exit code 125.; 389)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T23:57:29.002+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T23:57:29.039+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T23:57:29.044+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T00:18:36.923+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T00:18:37.035+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-25T00:18:37.077+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-25T00:18:37.078+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T00:18:37.146+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-08 00:00:00+00:00
[2025-03-25T00:18:37.192+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp057y_5ti']
[2025-03-25T00:18:37.200+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask php_app2
[2025-03-25T00:18:37.243+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=429) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T00:18:37.244+0000] {standard_task_runner.py:72} INFO - Started process 439 to run task
[2025-03-25T00:18:37.587+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [running]> on host 0f77abd8a5ce
[2025-03-25T00:18:39.195+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-25T00:18:39.198+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T00:18:39.265+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T00:18:39.309+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:18:39.369+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250325T001837, end_date=20250325T001839
[2025-03-25T00:18:39.888+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T00:18:39.894+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task php_app2 (Failed to establish connection to any given Docker hosts.; 439)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:18:39.964+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T00:18:40.104+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T00:25:44.025+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T00:25:44.235+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-25T00:25:44.326+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-25T00:25:44.326+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T00:25:44.487+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-08 00:00:00+00:00
[2025-03-25T00:25:44.607+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=238) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T00:25:44.609+0000] {standard_task_runner.py:72} INFO - Started process 254 to run task
[2025-03-25T00:25:44.597+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp5y45eqwf']
[2025-03-25T00:25:44.633+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask php_app2
[2025-03-25T00:25:45.108+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [running]> on host 7e2e363232cf
[2025-03-25T00:25:45.900+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-25T00:25:45.902+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T00:25:45.980+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T00:25:46.043+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:25:46.070+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250325T002544, end_date=20250325T002546
[2025-03-25T00:25:46.224+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T00:25:46.225+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task php_app2 (Failed to establish connection to any given Docker hosts.; 254)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:25:46.374+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T00:25:46.441+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T12:45:33.030+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T12:45:33.160+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-25T12:45:33.185+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-25T12:45:33.186+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T12:45:33.464+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-08 00:00:00+00:00
[2025-03-25T12:45:33.520+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=248) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T12:45:33.522+0000] {standard_task_runner.py:72} INFO - Started process 264 to run task
[2025-03-25T12:45:33.551+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmph34uedib']
[2025-03-25T12:45:33.569+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask php_app2
[2025-03-25T12:45:33.988+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [running]> on host c83c0958fca4
[2025-03-25T12:45:34.591+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-25T12:45:34.592+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T12:45:34.809+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T12:45:34.864+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T12:45:34.916+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250325T124533, end_date=20250325T124534
[2025-03-25T12:45:35.144+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T12:45:35.147+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task php_app2 (Failed to establish connection to any given Docker hosts.; 264)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T12:45:35.216+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T12:45:35.313+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T12:45:35.333+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T11:52:48.785+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T11:52:48.996+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-26T11:52:49.124+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-26T11:52:49.125+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T11:52:49.393+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-08 00:00:00+00:00
[2025-03-26T11:52:49.481+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=247) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T11:52:49.507+0000] {standard_task_runner.py:72} INFO - Started process 261 to run task
[2025-03-26T11:52:49.469+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpezy2xnjp']
[2025-03-26T11:52:49.515+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask php_app2
[2025-03-26T11:52:49.818+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [running]> on host c0a4d7e9da1a
[2025-03-26T11:52:50.624+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-26T11:52:50.625+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T11:52:50.691+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-26T11:52:50.719+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T11:52:50.772+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250326T115249, end_date=20250326T115250
[2025-03-26T11:52:50.905+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T11:52:50.908+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task php_app2 (Failed to establish connection to any given Docker hosts.; 261)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T11:52:51.000+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-26T11:52:51.110+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T11:52:51.135+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T13:18:10.157+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T13:18:10.221+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-26T13:18:10.256+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-26T13:18:10.257+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T13:18:10.333+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-08 00:00:00+00:00
[2025-03-26T13:18:10.367+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpmr5s4xer']
[2025-03-26T13:18:10.376+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask php_app2
[2025-03-26T13:18:10.376+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1270) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T13:18:10.377+0000] {standard_task_runner.py:72} INFO - Started process 1285 to run task
[2025-03-26T13:18:10.557+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [running]> on host f731374053d7
[2025-03-26T13:18:10.728+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-26T13:18:10.729+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T13:18:10.763+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[2025-03-26T13:18:10.775+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T13:18:10.787+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250326T131810, end_date=20250326T131810
[2025-03-26T13:18:10.830+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T13:18:10.831+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task php_app2 (Failed to establish connection to any given Docker hosts.; 1285)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T13:18:10.849+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-26T13:18:10.881+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T13:18:10.885+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T13:38:24.430+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T13:38:24.582+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-26T13:38:24.602+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [queued]>
[2025-03-26T13:38:24.603+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T13:38:24.748+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-08 00:00:00+00:00
[2025-03-26T13:38:24.788+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=283) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T13:38:24.790+0000] {standard_task_runner.py:72} INFO - Started process 295 to run task
[2025-03-26T13:38:24.843+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-08T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmppadwfmes']
[2025-03-26T13:38:24.846+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask php_app2
[2025-03-26T13:38:25.178+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-08T00:00:00+00:00 [running]> on host 3d581a580455
[2025-03-26T13:38:25.883+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-08T00:00:00+00:00'
[2025-03-26T13:38:25.884+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T13:38:26.022+0000] {docker.py:345} INFO - Starting docker container from image php-app2
[2025-03-26T13:38:26.027+0000] {docker.py:353} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-03-26T13:38:30.471+0000] {docker.py:69} INFO - array(18) {
[2025-03-26T13:38:30.472+0000] {docker.py:69} INFO -   [0]=>
[2025-03-26T13:38:30.472+0000] {docker.py:69} INFO -   object(stdClass)#2 (3) {
[2025-03-26T13:38:30.473+0000] {docker.py:69} INFO -     [
[2025-03-26T13:38:30.473+0000] {docker.py:69} INFO - "contador"]=>
[2025-03-26T13:38:30.474+0000] {docker.py:69} INFO -     int(0)
[2025-03-26T13:38:30.474+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.474+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.474+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.475+0000] {docker.py:69} INFO -     int(1742852307)
[2025-03-26T13:38:30.475+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.475+0000] {docker.py:69} INFO -   [1]=>
[2025-03-26T13:38:30.476+0000] {docker.py:69} INFO -   object(stdClass)#3 (3) {
[2025-03-26T13:38:30.476+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.476+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.477+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.477+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.478+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.478+0000] {docker.py:69} INFO -     int(1742852309)
[2025-03-26T13:38:30.478+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.479+0000] {docker.py:69} INFO -   [2]=>
[2025-03-26T13:38:30.479+0000] {docker.py:69} INFO -   object(stdClass)#4 (3) {
[2025-03-26T13:38:30.479+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.479+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.480+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.480+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.480+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.480+0000] {docker.py:69} INFO -     int(1742852311)
[2025-03-26T13:38:30.481+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.481+0000] {docker.py:69} INFO -   [3]=>
[2025-03-26T13:38:30.482+0000] {docker.py:69} INFO -   object(stdClass)#5 (3) {
[2025-03-26T13:38:30.482+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.482+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.483+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.483+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.484+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.484+0000] {docker.py:69} INFO -     int(1742852314)
[2025-03-26T13:38:30.484+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.485+0000] {docker.py:69} INFO -   [4]=>
[2025-03-26T13:38:30.485+0000] {docker.py:69} INFO -   object(stdClass)#6 (3) {
[2025-03-26T13:38:30.486+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.486+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.487+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.488+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.488+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.488+0000] {docker.py:69} INFO -     int(1742996301)
[2025-03-26T13:38:30.489+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.490+0000] {docker.py:69} INFO -   [5]=>
[2025-03-26T13:38:30.490+0000] {docker.py:69} INFO -   object(stdClass)#7 (3) {
[2025-03-26T13:38:30.491+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.491+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.492+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.492+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.493+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.493+0000] {docker.py:69} INFO -     int(1742996302)
[2025-03-26T13:38:30.494+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.494+0000] {docker.py:69} INFO -   [6]=>
[2025-03-26T13:38:30.494+0000] {docker.py:69} INFO -   object(stdClass)#8 (3) {
[2025-03-26T13:38:30.498+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.498+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.499+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.499+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.500+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.502+0000] {docker.py:69} INFO -     int(1742996302)
[2025-03-26T13:38:30.503+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.504+0000] {docker.py:69} INFO -   [7]=>
[2025-03-26T13:38:30.504+0000] {docker.py:69} INFO -   object(stdClass)#9 (3) {
[2025-03-26T13:38:30.505+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.505+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.506+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.506+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.506+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.507+0000] {docker.py:69} INFO -     int(1742996303)
[2025-03-26T13:38:30.507+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.508+0000] {docker.py:69} INFO -   [8]=>
[2025-03-26T13:38:30.511+0000] {docker.py:69} INFO -   object(stdClass)#10 (3) {
[2025-03-26T13:38:30.512+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.512+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.513+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.513+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.514+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.517+0000] {docker.py:69} INFO -     int(1742996304)
[2025-03-26T13:38:30.517+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.518+0000] {docker.py:69} INFO -   [9]=>
[2025-03-26T13:38:30.524+0000] {docker.py:69} INFO -   object(stdClass)#11 (3) {
[2025-03-26T13:38:30.525+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.528+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.528+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.529+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.529+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.530+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:30.530+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.531+0000] {docker.py:69} INFO -   [10]=>
[2025-03-26T13:38:30.532+0000] {docker.py:69} INFO -   object(stdClass)#12 (3) {
[2025-03-26T13:38:30.532+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.532+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.533+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.533+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.534+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.534+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:30.535+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.535+0000] {docker.py:69} INFO -   [11]=>
[2025-03-26T13:38:30.535+0000] {docker.py:69} INFO -   object(stdClass)#13 (3) {
[2025-03-26T13:38:30.536+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.536+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.537+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.537+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.538+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.538+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:30.538+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.539+0000] {docker.py:69} INFO -   [12]=>
[2025-03-26T13:38:30.539+0000] {docker.py:69} INFO -   object(stdClass)#14 (3) {
[2025-03-26T13:38:30.539+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.540+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.540+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.541+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.541+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.542+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:30.542+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.542+0000] {docker.py:69} INFO -   [13]=>
[2025-03-26T13:38:30.543+0000] {docker.py:69} INFO -   object(stdClass)#15 (3) {
[2025-03-26T13:38:30.544+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.545+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.545+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.546+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.546+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.546+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:30.547+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.547+0000] {docker.py:69} INFO -   [14]=>
[2025-03-26T13:38:30.547+0000] {docker.py:69} INFO -   object(stdClass)#16 (3) {
[2025-03-26T13:38:30.548+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.549+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.549+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.549+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.559+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.561+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:30.563+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.566+0000] {docker.py:69} INFO -   [15]=>
[2025-03-26T13:38:30.567+0000] {docker.py:69} INFO -   object(stdClass)#17 (3) {
[2025-03-26T13:38:30.567+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.568+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.570+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.571+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.573+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.574+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:30.574+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.575+0000] {docker.py:69} INFO -   [16]=>
[2025-03-26T13:38:30.575+0000] {docker.py:69} INFO -   object(stdClass)#18 (3) {
[2025-03-26T13:38:30.576+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.577+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.577+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.578+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.578+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.579+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:30.579+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.580+0000] {docker.py:69} INFO -   [17]=>
[2025-03-26T13:38:30.580+0000] {docker.py:69} INFO -   array(3) {
[2025-03-26T13:38:30.581+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.581+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.583+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.584+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.584+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.585+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:30.585+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.585+0000] {docker.py:69} INFO - }
[2025-03-26T13:38:32.322+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T13:38:32.323+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-08T00:00:00+00:00, execution_date=20240308T000000, start_date=20250326T133824, end_date=20250326T133832
[2025-03-26T13:38:32.822+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-26T13:38:32.871+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T13:38:32.997+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
