[2025-03-24T22:19:25.267+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:19:25.449+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T22:19:25.516+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T22:19:25.518+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:19:25.595+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app2> on 2024-03-09 00:00:00+00:00
[2025-03-24T22:19:25.641+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4950) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:19:25.658+0000] {standard_task_runner.py:72} INFO - Started process 4978 to run task
[2025-03-24T22:19:25.658+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpcuyisvoa']
[2025-03-24T22:19:25.678+0000] {standard_task_runner.py:105} INFO - Job 141: Subtask php_app2
[2025-03-24T22:19:26.488+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:19:27.447+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andreeppinghaus' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-24T22:19:27.448+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:19:27.822+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:19:27.841+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sudo docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app2']
[2025-03-24T22:19:27.922+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:19:28.106+0000] {subprocess.py:106} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2025-03-24T22:19:28.115+0000] {subprocess.py:106} INFO - sudo: a password is required
[2025-03-24T22:19:28.119+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-24T22:19:28.209+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:19:28.257+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250324T221925, end_date=20250324T221928
[2025-03-24T22:19:28.392+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:19:28.393+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 141 for task php_app2 (Bash command failed. The command returned a non-zero exit code 1.; 4978)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:19:28.440+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:19:28.532+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T22:19:28.549+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T22:24:19.863+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:24:20.033+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T22:24:20.093+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T22:24:20.094+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:24:20.532+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app2> on 2024-03-09 00:00:00+00:00
[2025-03-24T22:24:20.618+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5286) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:24:20.633+0000] {standard_task_runner.py:72} INFO - Started process 5320 to run task
[2025-03-24T22:24:20.620+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpqtaf7h53']
[2025-03-24T22:24:20.640+0000] {standard_task_runner.py:105} INFO - Job 159: Subtask php_app2
[2025-03-24T22:24:20.981+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:24:21.477+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-24T22:24:21.483+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:24:21.623+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:24:21.626+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sudo docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app2']
[2025-03-24T22:24:21.730+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:24:21.903+0000] {subprocess.py:106} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2025-03-24T22:24:21.906+0000] {subprocess.py:106} INFO - sudo: a password is required
[2025-03-24T22:24:21.907+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-24T22:24:22.063+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:24:22.086+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250324T222420, end_date=20250324T222422
[2025-03-24T22:24:22.458+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:24:22.462+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 159 for task php_app2 (Bash command failed. The command returned a non-zero exit code 1.; 5320)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:24:22.620+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:24:22.987+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T22:24:23.053+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T22:27:27.377+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:27:27.640+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T22:27:27.662+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T22:27:27.663+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:27:27.704+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app2> on 2024-03-09 00:00:00+00:00
[2025-03-24T22:27:27.722+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5717) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:27:27.723+0000] {standard_task_runner.py:72} INFO - Started process 5751 to run task
[2025-03-24T22:27:27.755+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpxd3i05od']
[2025-03-24T22:27:27.793+0000] {standard_task_runner.py:105} INFO - Job 192: Subtask php_app2
[2025-03-24T22:27:28.137+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:27:28.906+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-24T22:27:28.912+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:27:29.390+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:27:29.395+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app2']
[2025-03-24T22:27:29.506+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:27:29.596+0000] {subprocess.py:106} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2025-03-24T22:27:29.597+0000] {subprocess.py:106} INFO - See 'docker run --help'.
[2025-03-24T22:27:29.609+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2025-03-24T22:27:29.677+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T22:27:29.717+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250324T222727, end_date=20250324T222729
[2025-03-24T22:27:29.896+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:27:29.897+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 192 for task php_app2 (Bash command failed. The command returned a non-zero exit code 125.; 5751)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T22:27:29.939+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:27:30.038+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T23:57:29.458+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T23:57:29.508+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T23:57:29.536+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T23:57:29.537+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T23:57:29.895+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app2> on 2024-03-09 00:00:00+00:00
[2025-03-24T23:57:29.927+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpnf_ltft2']
[2025-03-24T23:57:29.932+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask php_app2
[2025-03-24T23:57:29.980+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=432) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T23:57:29.985+0000] {standard_task_runner.py:72} INFO - Started process 443 to run task
[2025-03-24T23:57:30.083+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [running]> on host 8e89fdaa3360
[2025-03-24T23:57:30.353+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-24T23:57:30.354+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T23:57:30.431+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T23:57:30.435+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app2']
[2025-03-24T23:57:30.492+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T23:57:30.590+0000] {subprocess.py:106} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2025-03-24T23:57:30.595+0000] {subprocess.py:106} INFO - See 'docker run --help'.
[2025-03-24T23:57:30.596+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2025-03-24T23:57:30.627+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T23:57:30.662+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250324T235729, end_date=20250324T235730
[2025-03-24T23:57:30.884+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T23:57:30.885+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task php_app2 (Bash command failed. The command returned a non-zero exit code 125.; 443)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T23:57:30.933+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T23:57:31.099+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T23:57:31.163+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T00:18:36.802+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T00:18:36.993+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-25T00:18:37.067+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-25T00:18:37.067+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T00:18:37.593+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-09 00:00:00+00:00
[2025-03-25T00:18:37.728+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp3yhfxqfi']
[2025-03-25T00:18:37.753+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask php_app2
[2025-03-25T00:18:37.843+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=430) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T00:18:37.907+0000] {standard_task_runner.py:72} INFO - Started process 441 to run task
[2025-03-25T00:18:38.445+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [running]> on host 0f77abd8a5ce
[2025-03-25T00:18:39.744+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-25T00:18:39.745+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T00:18:39.965+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T00:18:40.132+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:18:40.175+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250325T001836, end_date=20250325T001840
[2025-03-25T00:18:40.426+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T00:18:40.427+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task php_app2 (Failed to establish connection to any given Docker hosts.; 441)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:18:40.510+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T00:18:40.939+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T00:18:40.974+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T00:25:44.309+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T00:25:44.396+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-25T00:25:44.430+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-25T00:25:44.434+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T00:25:44.541+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-09 00:00:00+00:00
[2025-03-25T00:25:44.567+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpqnxnw9qs']
[2025-03-25T00:25:44.577+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask php_app2
[2025-03-25T00:25:44.613+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=241) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T00:25:44.614+0000] {standard_task_runner.py:72} INFO - Started process 255 to run task
[2025-03-25T00:25:44.931+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [running]> on host 7e2e363232cf
[2025-03-25T00:25:45.630+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-25T00:25:45.631+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T00:25:45.759+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T00:25:45.787+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:25:45.838+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250325T002544, end_date=20250325T002545
[2025-03-25T00:25:46.214+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T00:25:46.219+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task php_app2 (Failed to establish connection to any given Docker hosts.; 255)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:25:46.292+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T00:25:46.413+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T00:25:46.420+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T12:45:33.782+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T12:45:34.029+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-25T12:45:34.079+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-25T12:45:34.080+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T12:45:34.364+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-09 00:00:00+00:00
[2025-03-25T12:45:34.444+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=255) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T12:45:34.447+0000] {standard_task_runner.py:72} INFO - Started process 275 to run task
[2025-03-25T12:45:34.483+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpx9dsn1uh']
[2025-03-25T12:45:34.487+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask php_app2
[2025-03-25T12:45:34.802+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [running]> on host c83c0958fca4
[2025-03-25T12:45:35.294+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-25T12:45:35.304+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T12:45:35.372+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T12:45:35.424+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T12:45:35.467+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250325T124534, end_date=20250325T124535
[2025-03-25T12:45:35.714+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T12:45:35.716+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 20 for task php_app2 (Failed to establish connection to any given Docker hosts.; 275)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T12:45:35.773+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T12:45:35.818+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T12:45:35.825+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T11:52:49.989+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T11:52:50.581+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-26T11:52:50.702+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-26T11:52:50.710+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T11:52:50.839+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-09 00:00:00+00:00
[2025-03-26T11:52:50.923+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=249) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T11:52:50.926+0000] {standard_task_runner.py:72} INFO - Started process 271 to run task
[2025-03-26T11:52:50.915+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpjr9xnpnv']
[2025-03-26T11:52:50.929+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask php_app2
[2025-03-26T11:52:51.225+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [running]> on host c0a4d7e9da1a
[2025-03-26T11:52:51.541+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-26T11:52:51.542+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T11:52:51.587+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-26T11:52:51.604+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T11:52:51.624+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250326T115250, end_date=20250326T115251
[2025-03-26T11:52:51.695+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T11:52:51.697+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task php_app2 (Failed to establish connection to any given Docker hosts.; 271)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T11:52:51.728+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-26T11:52:51.756+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T11:52:51.763+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T13:38:27.867+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T13:38:27.913+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-26T13:38:27.924+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-26T13:38:27.925+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T13:38:27.966+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-09 00:00:00+00:00
[2025-03-26T13:38:27.999+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=300) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T13:38:28.001+0000] {standard_task_runner.py:72} INFO - Started process 314 to run task
[2025-03-26T13:38:28.022+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpservd34q']
[2025-03-26T13:38:28.036+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask php_app2
[2025-03-26T13:38:28.357+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-09T00:00:00+00:00 [running]> on host 3d581a580455
[2025-03-26T13:38:28.943+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-26T13:38:28.944+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T13:38:29.146+0000] {docker.py:345} INFO - Starting docker container from image php-app2
[2025-03-26T13:38:29.152+0000] {docker.py:353} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-03-26T13:38:32.557+0000] {docker.py:69} INFO - array(22) {
[2025-03-26T13:38:32.559+0000] {docker.py:69} INFO -   [0]=>
[2025-03-26T13:38:32.560+0000] {docker.py:69} INFO -   object(stdClass)#2 (3) {
[2025-03-26T13:38:32.560+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.561+0000] {docker.py:69} INFO -     int(0)
[2025-03-26T13:38:32.561+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.561+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:32.562+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.565+0000] {docker.py:69} INFO -     int(1742852307)
[2025-03-26T13:38:32.565+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.568+0000] {docker.py:69} INFO -   [1]=>
[2025-03-26T13:38:32.571+0000] {docker.py:69} INFO -   object(stdClass)#3 (3) {
[2025-03-26T13:38:32.571+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.574+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.574+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.577+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:32.577+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.578+0000] {docker.py:69} INFO -     int(1742852309)
[2025-03-26T13:38:32.578+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.579+0000] {docker.py:69} INFO -   [2]=>
[2025-03-26T13:38:32.580+0000] {docker.py:69} INFO -   object(stdClass)#4 (3) {
[2025-03-26T13:38:32.580+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.581+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.603+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.603+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:32.604+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.616+0000] {docker.py:69} INFO -     int(1742852311)
[2025-03-26T13:38:32.622+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.632+0000] {docker.py:69} INFO -   [3]=>
[2025-03-26T13:38:32.645+0000] {docker.py:69} INFO -   object(stdClass)#5 (3) {
[2025-03-26T13:38:32.661+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.664+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.664+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.665+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:32.684+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.685+0000] {docker.py:69} INFO -     int(1742852314)
[2025-03-26T13:38:32.686+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.686+0000] {docker.py:69} INFO -   [4]=>
[2025-03-26T13:38:32.687+0000] {docker.py:69} INFO -   object(stdClass)#6 (3) {
[2025-03-26T13:38:32.687+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.688+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.688+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.689+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:32.689+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.690+0000] {docker.py:69} INFO -     int(1742996301)
[2025-03-26T13:38:32.690+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.691+0000] {docker.py:69} INFO -   [5]=>
[2025-03-26T13:38:32.691+0000] {docker.py:69} INFO -   object(stdClass)#7 (3) {
[2025-03-26T13:38:32.691+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.692+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.692+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.693+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:32.693+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.694+0000] {docker.py:69} INFO -     int(1742996302)
[2025-03-26T13:38:32.694+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.695+0000] {docker.py:69} INFO -   [6]=>
[2025-03-26T13:38:32.695+0000] {docker.py:69} INFO -   object(stdClass)#8 (3) {
[2025-03-26T13:38:32.696+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.696+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.696+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.697+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:32.697+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.698+0000] {docker.py:69} INFO -     int(1742996302)
[2025-03-26T13:38:32.698+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.698+0000] {docker.py:69} INFO -   [7]=>
[2025-03-26T13:38:32.699+0000] {docker.py:69} INFO -   object(stdClass)#9 (3) {
[2025-03-26T13:38:32.699+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.699+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.700+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.700+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:32.700+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.701+0000] {docker.py:69} INFO -     int(1742996303)
[2025-03-26T13:38:32.701+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.702+0000] {docker.py:69} INFO -   [8]=>
[2025-03-26T13:38:32.702+0000] {docker.py:69} INFO -   object(stdClass)#10 (3) {
[2025-03-26T13:38:32.702+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.703+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.703+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.703+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:32.704+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.704+0000] {docker.py:69} INFO -     int(1742996304)
[2025-03-26T13:38:32.704+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.704+0000] {docker.py:69} INFO -   [9]=>
[2025-03-26T13:38:32.705+0000] {docker.py:69} INFO -   object(stdClass)#11 (3) {
[2025-03-26T13:38:32.705+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.705+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.706+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.706+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:32.706+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.707+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:32.707+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.707+0000] {docker.py:69} INFO -   [10]=>
[2025-03-26T13:38:32.708+0000] {docker.py:69} INFO -   object(stdClass)#12 (3) {
[2025-03-26T13:38:32.708+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.709+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.710+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.710+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:32.710+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.711+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:32.712+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.713+0000] {docker.py:69} INFO -   [11]=>
[2025-03-26T13:38:32.713+0000] {docker.py:69} INFO -   object(stdClass)#13 (3) {
[2025-03-26T13:38:32.713+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.714+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.714+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.715+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:32.715+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.716+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:32.717+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.717+0000] {docker.py:69} INFO -   [12]=>
[2025-03-26T13:38:32.718+0000] {docker.py:69} INFO -   object(stdClass)#14 (3) {
[2025-03-26T13:38:32.718+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.719+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.719+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.719+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:32.720+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.720+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:32.720+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.721+0000] {docker.py:69} INFO -   [13]=>
[2025-03-26T13:38:32.721+0000] {docker.py:69} INFO -   object(stdClass)#15 (3) {
[2025-03-26T13:38:32.721+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.722+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.722+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.723+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:32.723+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.724+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:32.724+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.724+0000] {docker.py:69} INFO -   [14]=>
[2025-03-26T13:38:32.725+0000] {docker.py:69} INFO -   object(stdClass)#16 (3) {
[2025-03-26T13:38:32.725+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.725+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.726+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.727+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:32.727+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.728+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:32.728+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.728+0000] {docker.py:69} INFO -   [15]=>
[2025-03-26T13:38:32.729+0000] {docker.py:69} INFO -   object(stdClass)#17 (3) {
[2025-03-26T13:38:32.729+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.729+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.732+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.733+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:32.733+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.733+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:32.734+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.734+0000] {docker.py:69} INFO -   [16]=>
[2025-03-26T13:38:32.734+0000] {docker.py:69} INFO -   object(stdClass)#18 (3) {
[2025-03-26T13:38:32.735+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.735+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.736+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.736+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:32.737+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.737+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:32.738+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.738+0000] {docker.py:69} INFO -   [17]=>
[2025-03-26T13:38:32.738+0000] {docker.py:69} INFO -   object(stdClass)#19 (3) {
[2025-03-26T13:38:32.739+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.739+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.740+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.740+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:32.740+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.741+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:32.741+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.741+0000] {docker.py:69} INFO -   [18]=>
[2025-03-26T13:38:32.742+0000] {docker.py:69} INFO -   object(stdClass)#20 (3) {
[2025-03-26T13:38:32.742+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.742+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.743+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.744+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:32.745+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.746+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:32.746+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.746+0000] {docker.py:69} INFO -   [19]=>
[2025-03-26T13:38:32.747+0000] {docker.py:69} INFO -   object(stdClass)#21 (3) {
[2025-03-26T13:38:32.748+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.749+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.751+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.752+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:32.752+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.753+0000] {docker.py:69} INFO -     int(1742996311)
[2025-03-26T13:38:32.763+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.764+0000] {docker.py:69} INFO -   [20]=>
[2025-03-26T13:38:32.766+0000] {docker.py:69} INFO -   object(stdClass)#22 (3) {
[2025-03-26T13:38:32.769+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.769+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.770+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.770+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:32.773+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.773+0000] {docker.py:69} INFO -     int(1742996311)
[2025-03-26T13:38:32.774+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.774+0000] {docker.py:69} INFO -   [21]=>
[2025-03-26T13:38:32.775+0000] {docker.py:69} INFO -   array(3) {
[2025-03-26T13:38:32.776+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:32.776+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:32.776+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:32.777+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:32.777+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:32.784+0000] {docker.py:69} INFO -     int(1742996312)
[2025-03-26T13:38:32.784+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:32.785+0000] {docker.py:69} INFO - }
[2025-03-26T13:38:33.878+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T13:38:33.878+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250326T133827, end_date=20250326T133833
[2025-03-26T13:38:34.100+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-26T13:38:34.125+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T13:38:34.131+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
