[2025-03-24T22:19:09.448+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:19:09.568+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T22:19:09.670+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T22:19:09.680+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:19:09.872+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app1> on 2024-03-09 00:00:00+00:00
[2025-03-24T22:19:09.941+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpfmroug9j']
[2025-03-24T22:19:09.945+0000] {standard_task_runner.py:105} INFO - Job 119: Subtask php_app1
[2025-03-24T22:19:09.961+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4857) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:19:09.962+0000] {standard_task_runner.py:72} INFO - Started process 4875 to run task
[2025-03-24T22:19:10.352+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:19:11.012+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andreeppinghaus' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-24T22:19:11.020+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:19:11.132+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:19:11.133+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sudo docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app1']
[2025-03-24T22:19:11.180+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:19:11.207+0000] {subprocess.py:106} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2025-03-24T22:19:11.208+0000] {subprocess.py:106} INFO - sudo: a password is required
[2025-03-24T22:19:11.210+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-24T22:19:11.251+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:19:11.304+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250324T221909, end_date=20250324T221911
[2025-03-24T22:19:11.482+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:19:11.483+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 119 for task php_app1 (Bash command failed. The command returned a non-zero exit code 1.; 4875)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:19:11.530+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:19:11.573+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T22:24:20.024+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:24:20.140+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T22:24:20.204+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T22:24:20.209+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:24:20.591+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app1> on 2024-03-09 00:00:00+00:00
[2025-03-24T22:24:20.647+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpvgnlji4w']
[2025-03-24T22:24:20.667+0000] {standard_task_runner.py:105} INFO - Job 160: Subtask php_app1
[2025-03-24T22:24:20.689+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5287) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:24:20.706+0000] {standard_task_runner.py:72} INFO - Started process 5321 to run task
[2025-03-24T22:24:21.108+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:24:21.865+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-24T22:24:21.866+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:24:21.914+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:24:21.915+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sudo docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app1']
[2025-03-24T22:24:21.954+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:24:21.985+0000] {subprocess.py:106} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2025-03-24T22:24:21.986+0000] {subprocess.py:106} INFO - sudo: a password is required
[2025-03-24T22:24:21.987+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-24T22:24:22.101+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:24:22.182+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250324T222420, end_date=20250324T222422
[2025-03-24T22:24:22.524+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:24:22.534+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 160 for task php_app1 (Bash command failed. The command returned a non-zero exit code 1.; 5321)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:24:22.682+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:24:22.800+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T22:27:26.979+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:27:27.101+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T22:27:27.124+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T22:27:27.125+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:27:27.187+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app1> on 2024-03-09 00:00:00+00:00
[2025-03-24T22:27:27.362+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5708) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:27:27.364+0000] {standard_task_runner.py:72} INFO - Started process 5748 to run task
[2025-03-24T22:27:27.380+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpaa97euzn']
[2025-03-24T22:27:27.383+0000] {standard_task_runner.py:105} INFO - Job 190: Subtask php_app1
[2025-03-24T22:27:27.847+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:27:28.171+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-24T22:27:28.173+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:27:28.273+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:27:28.282+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app1']
[2025-03-24T22:27:28.350+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:27:28.465+0000] {subprocess.py:106} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2025-03-24T22:27:28.467+0000] {subprocess.py:106} INFO - See 'docker run --help'.
[2025-03-24T22:27:28.476+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2025-03-24T22:27:28.600+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T22:27:28.714+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250324T222727, end_date=20250324T222728
[2025-03-24T22:27:29.092+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:27:29.094+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 190 for task php_app1 (Bash command failed. The command returned a non-zero exit code 125.; 5748)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T22:27:29.145+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:27:29.488+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T22:27:29.537+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T23:57:29.459+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T23:57:29.518+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T23:57:29.539+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-24T23:57:29.539+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T23:57:29.861+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app1> on 2024-03-09 00:00:00+00:00
[2025-03-24T23:57:29.886+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmptb0fg_gf']
[2025-03-24T23:57:29.892+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask php_app1
[2025-03-24T23:57:29.892+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=433) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T23:57:29.899+0000] {standard_task_runner.py:72} INFO - Started process 440 to run task
[2025-03-24T23:57:30.048+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [running]> on host 8e89fdaa3360
[2025-03-24T23:57:30.359+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-24T23:57:30.360+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T23:57:30.434+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T23:57:30.435+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app1']
[2025-03-24T23:57:30.454+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T23:57:30.517+0000] {subprocess.py:106} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2025-03-24T23:57:30.518+0000] {subprocess.py:106} INFO - See 'docker run --help'.
[2025-03-24T23:57:30.520+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2025-03-24T23:57:30.582+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T23:57:30.637+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250324T235729, end_date=20250324T235730
[2025-03-24T23:57:30.866+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T23:57:30.868+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 20 for task php_app1 (Bash command failed. The command returned a non-zero exit code 125.; 440)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T23:57:30.938+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T23:57:31.042+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T00:18:37.285+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T00:18:37.403+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-25T00:18:37.490+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-25T00:18:37.490+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T00:18:37.675+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-09 00:00:00+00:00
[2025-03-25T00:18:37.814+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpdn6bu9oc']
[2025-03-25T00:18:37.819+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask php_app1
[2025-03-25T00:18:37.859+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=432) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T00:18:37.861+0000] {standard_task_runner.py:72} INFO - Started process 444 to run task
[2025-03-25T00:18:38.563+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [running]> on host 0f77abd8a5ce
[2025-03-25T00:18:40.054+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-25T00:18:40.055+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T00:18:40.106+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T00:18:40.153+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:18:40.254+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250325T001837, end_date=20250325T001840
[2025-03-25T00:18:40.559+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T00:18:40.560+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task php_app1 (Failed to establish connection to any given Docker hosts.; 444)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:18:40.748+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T00:18:40.874+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T00:25:44.592+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T00:25:44.654+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-25T00:25:44.681+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-25T00:25:44.682+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T00:25:44.730+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-09 00:00:00+00:00
[2025-03-25T00:25:44.760+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=240) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T00:25:44.763+0000] {standard_task_runner.py:72} INFO - Started process 258 to run task
[2025-03-25T00:25:44.758+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpz6w2lfg5']
[2025-03-25T00:25:44.770+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask php_app1
[2025-03-25T00:25:45.040+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [running]> on host 7e2e363232cf
[2025-03-25T00:25:46.165+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-25T00:25:46.167+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T00:25:46.239+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T00:25:46.268+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:25:46.302+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250325T002544, end_date=20250325T002546
[2025-03-25T00:25:46.474+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T00:25:46.475+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 20 for task php_app1 (Failed to establish connection to any given Docker hosts.; 258)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:25:46.502+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T00:25:46.635+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T00:25:46.655+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T12:45:33.555+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T12:45:33.654+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-25T12:45:33.708+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-25T12:45:33.708+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T12:45:33.785+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-09 00:00:00+00:00
[2025-03-25T12:45:33.830+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpr4jpwep_']
[2025-03-25T12:45:33.841+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask php_app1
[2025-03-25T12:45:33.859+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=253) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T12:45:33.873+0000] {standard_task_runner.py:72} INFO - Started process 272 to run task
[2025-03-25T12:45:34.107+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [running]> on host c83c0958fca4
[2025-03-25T12:45:34.937+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-25T12:45:34.938+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T12:45:35.036+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T12:45:35.078+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T12:45:35.112+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250325T124533, end_date=20250325T124535
[2025-03-25T12:45:35.285+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T12:45:35.291+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task php_app1 (Failed to establish connection to any given Docker hosts.; 272)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T12:45:35.380+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T12:45:35.489+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T12:45:35.503+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T11:52:49.434+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T11:52:49.516+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-26T11:52:49.544+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-26T11:52:49.545+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T11:52:49.589+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-09 00:00:00+00:00
[2025-03-26T11:52:49.630+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp5z9sp0pt']
[2025-03-26T11:52:49.643+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask php_app1
[2025-03-26T11:52:49.697+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=248) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T11:52:49.698+0000] {standard_task_runner.py:72} INFO - Started process 264 to run task
[2025-03-26T11:52:49.953+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [running]> on host c0a4d7e9da1a
[2025-03-26T11:52:50.984+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-26T11:52:50.986+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T11:52:51.054+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-26T11:52:51.086+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T11:52:51.163+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250326T115249, end_date=20250326T115251
[2025-03-26T11:52:51.308+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T11:52:51.308+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task php_app1 (Failed to establish connection to any given Docker hosts.; 264)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T11:52:51.375+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-26T11:52:51.438+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T11:52:51.447+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T13:38:27.547+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T13:38:27.611+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-26T13:38:27.622+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [queued]>
[2025-03-26T13:38:27.622+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T13:38:27.755+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app1> on 2024-03-09 00:00:00+00:00
[2025-03-26T13:38:27.806+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=301) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T13:38:27.807+0000] {standard_task_runner.py:72} INFO - Started process 310 to run task
[2025-03-26T13:38:27.803+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app1', 'scheduled__2024-03-09T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpzpwt8eni']
[2025-03-26T13:38:27.810+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask php_app1
[2025-03-26T13:38:28.116+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app1 scheduled__2024-03-09T00:00:00+00:00 [running]> on host 3d581a580455
[2025-03-26T13:38:28.586+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app1' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-09T00:00:00+00:00'
[2025-03-26T13:38:28.587+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T13:38:28.753+0000] {docker.py:345} INFO - Starting docker container from image php-app1
[2025-03-26T13:38:28.758+0000] {docker.py:353} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-03-26T13:38:31.448+0000] {docker.py:69} INFO - array(21) {
[2025-03-26T13:38:31.450+0000] {docker.py:69} INFO -   [0]=>
[2025-03-26T13:38:31.453+0000] {docker.py:69} INFO - 
[2025-03-26T13:38:31.454+0000] {docker.py:69} INFO - object(stdClass)#2 (3) {
[2025-03-26T13:38:31.454+0000] {docker.py:69} INFO -     [
[2025-03-26T13:38:31.455+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:31.455+0000] {docker.py:69} INFO - contador
[2025-03-26T13:38:31.456+0000] {docker.py:69} INFO - "
[2025-03-26T13:38:31.456+0000] {docker.py:69} INFO - ]=>
[2025-03-26T13:38:31.457+0000] {docker.py:69} INFO -     int(0)
[2025-03-26T13:38:31.457+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.458+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.458+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.458+0000] {docker.py:69} INFO -     int(1742852307)
[2025-03-26T13:38:31.459+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.459+0000] {docker.py:69} INFO -   [1]=>
[2025-03-26T13:38:31.459+0000] {docker.py:69} INFO -   object(stdClass)#3 (3) {
[2025-03-26T13:38:31.460+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.460+0000] {docker.py:69} INFO - int(1)
[2025-03-26T13:38:31.461+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.461+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.461+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.462+0000] {docker.py:69} INFO -     int(1742852309)
[2025-03-26T13:38:31.462+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.462+0000] {docker.py:69} INFO -   [2]=>
[2025-03-26T13:38:31.463+0000] {docker.py:69} INFO -   object(stdClass)#4 (3) {
[2025-03-26T13:38:31.463+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.464+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.464+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.465+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.465+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.465+0000] {docker.py:69} INFO -     int(1742852311)
[2025-03-26T13:38:31.466+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.466+0000] {docker.py:69} INFO -   [3]=>
[2025-03-26T13:38:31.467+0000] {docker.py:69} INFO -   object(stdClass)#5 (3) {
[2025-03-26T13:38:31.467+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.468+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.468+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.469+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.469+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.469+0000] {docker.py:69} INFO -     int(1742852314)
[2025-03-26T13:38:31.470+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.470+0000] {docker.py:69} INFO -   [4]=>
[2025-03-26T13:38:31.471+0000] {docker.py:69} INFO -   object(stdClass)#6 (3) {
[2025-03-26T13:38:31.471+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.472+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.472+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.472+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.472+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.473+0000] {docker.py:69} INFO -     int(1742996301)
[2025-03-26T13:38:31.473+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.473+0000] {docker.py:69} INFO -   [5]=>
[2025-03-26T13:38:31.474+0000] {docker.py:69} INFO -   object(stdClass)#7 (3) {
[2025-03-26T13:38:31.474+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.474+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.475+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.475+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.475+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.476+0000] {docker.py:69} INFO -     int(1742996302)
[2025-03-26T13:38:31.476+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.476+0000] {docker.py:69} INFO -   [6]=>
[2025-03-26T13:38:31.476+0000] {docker.py:69} INFO -   object(stdClass)#8 (3) {
[2025-03-26T13:38:31.477+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.478+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.478+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.478+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.479+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.479+0000] {docker.py:69} INFO -     int(1742996302)
[2025-03-26T13:38:31.480+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.480+0000] {docker.py:69} INFO -   [7]=>
[2025-03-26T13:38:31.480+0000] {docker.py:69} INFO -   object(stdClass)#9 (3) {
[2025-03-26T13:38:31.480+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.481+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.481+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.482+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.482+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.483+0000] {docker.py:69} INFO -     int(1742996303)
[2025-03-26T13:38:31.483+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.484+0000] {docker.py:69} INFO -   [8]=>
[2025-03-26T13:38:31.485+0000] {docker.py:69} INFO -   object(stdClass)#10 (3) {
[2025-03-26T13:38:31.485+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.486+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.487+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.489+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.490+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.491+0000] {docker.py:69} INFO -     int(1742996304)
[2025-03-26T13:38:31.492+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.493+0000] {docker.py:69} INFO -   [9]=>
[2025-03-26T13:38:31.494+0000] {docker.py:69} INFO -   object(stdClass)#11 (3) {
[2025-03-26T13:38:31.495+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.496+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.497+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.498+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.498+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.499+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:31.500+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.501+0000] {docker.py:69} INFO -   [10]=>
[2025-03-26T13:38:31.501+0000] {docker.py:69} INFO -   object(stdClass)#12 (3) {
[2025-03-26T13:38:31.502+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.502+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.503+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.504+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.504+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.505+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:31.506+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.506+0000] {docker.py:69} INFO -   [11]=>
[2025-03-26T13:38:31.507+0000] {docker.py:69} INFO -   object(stdClass)#13 (3) {
[2025-03-26T13:38:31.507+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.508+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.508+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.508+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.509+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.509+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:31.510+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.510+0000] {docker.py:69} INFO -   [12]=>
[2025-03-26T13:38:31.511+0000] {docker.py:69} INFO -   object(stdClass)#14 (3) {
[2025-03-26T13:38:31.511+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.511+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.512+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.512+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.513+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.514+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:31.514+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.514+0000] {docker.py:69} INFO -   [13]=>
[2025-03-26T13:38:31.514+0000] {docker.py:69} INFO -   object(stdClass)#15 (3) {
[2025-03-26T13:38:31.514+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.515+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.515+0000] {docker.py:69} INFO -     ["container
[2025-03-26T13:38:31.516+0000] {docker.py:69} INFO - "]=>
[2025-03-26T13:38:31.516+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.516+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.516+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:31.517+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.517+0000] {docker.py:69} INFO -   [14]=>
[2025-03-26T13:38:31.517+0000] {docker.py:69} INFO -   object(stdClass)#16 (3) {
[2025-03-26T13:38:31.517+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.517+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.518+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.518+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.518+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.518+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:31.519+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.519+0000] {docker.py:69} INFO -   [15]=>
[2025-03-26T13:38:31.519+0000] {docker.py:69} INFO -   object(stdClass)#17 (3) {
[2025-03-26T13:38:31.519+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.519+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.520+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.520+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.520+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.521+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:31.521+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.521+0000] {docker.py:69} INFO -   [16]=>
[2025-03-26T13:38:31.522+0000] {docker.py:69} INFO -   object(stdClass)#18 (3) {
[2025-03-26T13:38:31.522+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.522+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.523+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.523+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.523+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.524+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:31.524+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.525+0000] {docker.py:69} INFO -   [17]=>
[2025-03-26T13:38:31.525+0000] {docker.py:69} INFO -   object(stdClass)#19 (3) {
[2025-03-26T13:38:31.525+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.526+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.526+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.527+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.527+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.527+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:31.528+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.528+0000] {docker.py:69} INFO -   [18]=>
[2025-03-26T13:38:31.528+0000] {docker.py:69} INFO -   object(stdClass)#20 (3) {
[2025-03-26T13:38:31.529+0000] {docker.py:69} INFO -     [
[2025-03-26T13:38:31.529+0000] {docker.py:69} INFO - "contador"]=>
[2025-03-26T13:38:31.530+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.530+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.530+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:31.531+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.531+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:31.531+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.531+0000] {docker.py:69} INFO -   [19]=>
[2025-03-26T13:38:31.532+0000] {docker.py:69} INFO -   object(stdClass)#21 (3) {
[2025-03-26T13:38:31.532+0000] {docker.py:69} INFO -     ["contador
[2025-03-26T13:38:31.533+0000] {docker.py:69} INFO - "]=>
[2025-03-26T13:38:31.534+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.534+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.535+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.535+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.535+0000] {docker.py:69} INFO -     int(1742996311)
[2025-03-26T13:38:31.536+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.536+0000] {docker.py:69} INFO -   [20]=>
[2025-03-26T13:38:31.536+0000] {docker.py:69} INFO -   array(3) {
[2025-03-26T13:38:31.537+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:31.537+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:31.537+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:31.538+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:31.538+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:31.538+0000] {docker.py:69} INFO -     int(1742996311)
[2025-03-26T13:38:31.539+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:31.539+0000] {docker.py:69} INFO - }
[2025-03-26T13:38:33.428+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T13:38:33.429+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=containers1_dag, task_id=php_app1, run_id=scheduled__2024-03-09T00:00:00+00:00, execution_date=20240309T000000, start_date=20250326T133827, end_date=20250326T133833
[2025-03-26T13:38:33.759+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-26T13:38:33.833+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T13:38:33.876+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
