[2025-03-24T22:19:24.235+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:19:24.519+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-24T22:19:24.696+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-24T22:19:24.699+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:19:25.081+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app2> on 2024-03-07 00:00:00+00:00
[2025-03-24T22:19:25.169+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4952) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:19:25.170+0000] {standard_task_runner.py:72} INFO - Started process 4973 to run task
[2025-03-24T22:19:25.166+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmppxrk61vj']
[2025-03-24T22:19:25.176+0000] {standard_task_runner.py:105} INFO - Job 130: Subtask php_app2
[2025-03-24T22:19:25.589+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:19:26.270+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andreeppinghaus' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2025-03-24T22:19:26.306+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:19:26.453+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:19:26.454+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sudo docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app2']
[2025-03-24T22:19:26.584+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:19:26.682+0000] {subprocess.py:106} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2025-03-24T22:19:26.683+0000] {subprocess.py:106} INFO - sudo: a password is required
[2025-03-24T22:19:26.684+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-24T22:19:26.835+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:19:26.951+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-07T00:00:00+00:00, execution_date=20240307T000000, start_date=20250324T221924, end_date=20250324T221926
[2025-03-24T22:19:27.205+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:19:27.209+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 130 for task php_app2 (Bash command failed. The command returned a non-zero exit code 1.; 4973)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:19:27.344+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:19:27.636+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T22:19:27.667+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T22:24:18.325+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:24:18.497+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-24T22:24:18.605+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-24T22:24:18.606+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:24:18.674+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app2> on 2024-03-07 00:00:00+00:00
[2025-03-24T22:24:18.721+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5256) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:24:18.723+0000] {standard_task_runner.py:72} INFO - Started process 5284 to run task
[2025-03-24T22:24:18.746+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp5venvxt_']
[2025-03-24T22:24:18.782+0000] {standard_task_runner.py:105} INFO - Job 155: Subtask php_app2
[2025-03-24T22:24:19.165+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:24:19.807+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2025-03-24T22:24:19.808+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:24:19.858+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:24:19.859+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sudo docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app2']
[2025-03-24T22:24:19.910+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:24:20.018+0000] {subprocess.py:106} INFO - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[2025-03-24T22:24:20.025+0000] {subprocess.py:106} INFO - sudo: a password is required
[2025-03-24T22:24:20.032+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-24T22:24:20.122+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:24:20.166+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-07T00:00:00+00:00, execution_date=20240307T000000, start_date=20250324T222418, end_date=20250324T222420
[2025-03-24T22:24:20.365+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:24:20.366+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 155 for task php_app2 (Bash command failed. The command returned a non-zero exit code 1.; 5284)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-24T22:24:20.431+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:24:20.619+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T22:24:20.642+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T22:27:23.926+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T22:27:24.024+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-24T22:27:24.117+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-24T22:27:24.118+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T22:27:24.168+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app2> on 2024-03-07 00:00:00+00:00
[2025-03-24T22:27:24.230+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5608) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T22:27:24.237+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpxlmue0bg']
[2025-03-24T22:27:24.270+0000] {standard_task_runner.py:105} INFO - Job 188: Subtask php_app2
[2025-03-24T22:27:24.263+0000] {standard_task_runner.py:72} INFO - Started process 5643 to run task
[2025-03-24T22:27:24.867+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [running]> on host b9050090f7f5
[2025-03-24T22:27:25.681+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2025-03-24T22:27:25.688+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T22:27:25.781+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T22:27:25.782+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app2']
[2025-03-24T22:27:25.863+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T22:27:26.069+0000] {subprocess.py:106} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2025-03-24T22:27:26.070+0000] {subprocess.py:106} INFO - See 'docker run --help'.
[2025-03-24T22:27:26.083+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2025-03-24T22:27:26.326+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T22:27:26.471+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-07T00:00:00+00:00, execution_date=20240307T000000, start_date=20250324T222724, end_date=20250324T222726
[2025-03-24T22:27:27.038+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T22:27:27.046+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 188 for task php_app2 (Bash command failed. The command returned a non-zero exit code 125.; 5643)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T22:27:27.155+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T22:27:27.289+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T22:27:27.333+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-24T23:57:27.538+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T23:57:27.844+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-24T23:57:27.908+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-24T23:57:27.909+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-24T23:57:28.091+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): php_app2> on 2024-03-07 00:00:00+00:00
[2025-03-24T23:57:28.139+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpdrkbljq_']
[2025-03-24T23:57:28.142+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask php_app2
[2025-03-24T23:57:28.172+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=278) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T23:57:28.173+0000] {standard_task_runner.py:72} INFO - Started process 376 to run task
[2025-03-24T23:57:28.338+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [running]> on host 8e89fdaa3360
[2025-03-24T23:57:28.568+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2025-03-24T23:57:28.569+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T23:57:28.622+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T23:57:28.623+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker run -v $(pwd)/../in:/usr/src/app/in -v $(pwd):/usr/src/app php-app2']
[2025-03-24T23:57:28.654+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T23:57:28.695+0000] {subprocess.py:106} INFO - docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
[2025-03-24T23:57:28.698+0000] {subprocess.py:106} INFO - See 'docker run --help'.
[2025-03-24T23:57:28.700+0000] {subprocess.py:110} INFO - Command exited with return code 125
[2025-03-24T23:57:28.726+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T23:57:28.743+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-07T00:00:00+00:00, execution_date=20240307T000000, start_date=20250324T235727, end_date=20250324T235728
[2025-03-24T23:57:28.815+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T23:57:28.816+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task php_app2 (Bash command failed. The command returned a non-zero exit code 125.; 376)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 125.
[2025-03-24T23:57:28.843+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-24T23:57:28.860+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T00:18:28.419+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T00:18:28.514+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-25T00:18:28.574+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-25T00:18:28.575+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T00:18:28.645+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-07 00:00:00+00:00
[2025-03-25T00:18:28.734+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=414) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T00:18:28.737+0000] {standard_task_runner.py:72} INFO - Started process 421 to run task
[2025-03-25T00:18:28.745+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpar66qdzi']
[2025-03-25T00:18:28.786+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask php_app2
[2025-03-25T00:18:29.079+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [running]> on host 0f77abd8a5ce
[2025-03-25T00:18:29.450+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2025-03-25T00:18:29.451+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T00:18:29.526+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T00:18:29.553+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:18:29.584+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-07T00:00:00+00:00, execution_date=20240307T000000, start_date=20250325T001828, end_date=20250325T001829
[2025-03-25T00:18:29.686+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T00:18:29.689+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task php_app2 (Failed to establish connection to any given Docker hosts.; 421)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:18:29.719+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T00:18:29.760+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T00:18:29.769+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T00:25:43.204+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T00:25:43.309+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-25T00:25:43.399+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-25T00:25:43.416+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T00:25:43.786+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-07 00:00:00+00:00
[2025-03-25T00:25:43.885+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpge1xah4i']
[2025-03-25T00:25:43.906+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask php_app2
[2025-03-25T00:25:43.950+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=222) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T00:25:43.967+0000] {standard_task_runner.py:72} INFO - Started process 245 to run task
[2025-03-25T00:25:44.206+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [running]> on host 7e2e363232cf
[2025-03-25T00:25:44.983+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2025-03-25T00:25:44.990+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T00:25:45.222+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T00:25:45.257+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:25:45.338+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-07T00:00:00+00:00, execution_date=20240307T000000, start_date=20250325T002543, end_date=20250325T002545
[2025-03-25T00:25:45.659+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T00:25:45.669+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task php_app2 (Failed to establish connection to any given Docker hosts.; 245)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T00:25:45.775+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T00:25:45.833+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T00:25:45.846+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-25T12:45:31.493+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T12:45:31.644+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-25T12:45:31.708+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-25T12:45:31.712+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-25T12:45:31.965+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-07 00:00:00+00:00
[2025-03-25T12:45:32.041+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp5k648z2f']
[2025-03-25T12:45:32.059+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask php_app2
[2025-03-25T12:45:32.092+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=232) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-25T12:45:32.114+0000] {standard_task_runner.py:72} INFO - Started process 252 to run task
[2025-03-25T12:45:32.442+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [running]> on host c83c0958fca4
[2025-03-25T12:45:33.464+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2025-03-25T12:45:33.464+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T12:45:33.646+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-25T12:45:33.778+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T12:45:33.909+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-07T00:00:00+00:00, execution_date=20240307T000000, start_date=20250325T124531, end_date=20250325T124533
[2025-03-25T12:45:34.161+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T12:45:34.161+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task php_app2 (Failed to establish connection to any given Docker hosts.; 252)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-25T12:45:34.434+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T12:45:34.626+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T12:45:34.638+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T11:52:47.667+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T11:52:47.735+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-26T11:52:47.795+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-26T11:52:47.796+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T11:52:47.933+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-07 00:00:00+00:00
[2025-03-26T11:52:47.963+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=235) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T11:52:47.965+0000] {standard_task_runner.py:72} INFO - Started process 252 to run task
[2025-03-26T11:52:47.963+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp091bqbfc']
[2025-03-26T11:52:47.967+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask php_app2
[2025-03-26T11:52:48.385+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [running]> on host c0a4d7e9da1a
[2025-03-26T11:52:49.028+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2025-03-26T11:52:49.029+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T11:52:49.118+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2025-03-26T11:52:49.168+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T11:52:49.299+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-07T00:00:00+00:00, execution_date=20240307T000000, start_date=20250326T115247, end_date=20250326T115249
[2025-03-26T11:52:49.552+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T11:52:49.552+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task php_app2 (Failed to establish connection to any given Docker hosts.; 252)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T11:52:49.651+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-26T11:52:49.816+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T11:52:49.844+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T13:18:08.754+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T13:18:08.955+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-26T13:18:09.031+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-26T13:18:09.032+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T13:18:09.101+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-07 00:00:00+00:00
[2025-03-26T13:18:09.158+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmpepr0jve0']
[2025-03-26T13:18:09.162+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask php_app2
[2025-03-26T13:18:09.199+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1265) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T13:18:09.208+0000] {standard_task_runner.py:72} INFO - Started process 1277 to run task
[2025-03-26T13:18:09.509+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [running]> on host f731374053d7
[2025-03-26T13:18:09.948+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2025-03-26T13:18:09.950+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T13:18:10.038+0000] {docker.py:157} ERROR - Failed to establish connection to Docker host unix://var/run/docker.sock: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[2025-03-26T13:18:10.069+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T13:18:10.105+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-07T00:00:00+00:00, execution_date=20240307T000000, start_date=20250326T131808, end_date=20250326T131810
[2025-03-26T13:18:10.242+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T13:18:10.243+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task php_app2 (Failed to establish connection to any given Docker hosts.; 1277)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 467, in execute
    if self.force_pull or not self.cli.images(name=self.image):
                              ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 341, in cli
    return self.hook.api_client
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 998, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/hooks/docker.py", line 161, in api_client
    raise AirflowException("Failed to establish connection to any given Docker hosts.")
airflow.exceptions.AirflowException: Failed to establish connection to any given Docker hosts.
[2025-03-26T13:18:10.327+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-26T13:18:10.422+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T13:18:10.436+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-26T13:38:23.199+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T13:38:23.575+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-26T13:38:23.690+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-03-26T13:38:23.690+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-26T13:38:24.128+0000] {taskinstance.py:2890} INFO - Executing <Task(DockerOperator): php_app2> on 2024-03-07 00:00:00+00:00
[2025-03-26T13:38:24.160+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'containers1_dag', 'php_app2', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/containers1_dag.py', '--cfg-path', '/tmp/tmp_jhwlmgd']
[2025-03-26T13:38:24.189+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask php_app2
[2025-03-26T13:38:24.212+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=271) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-26T13:38:24.220+0000] {standard_task_runner.py:72} INFO - Started process 293 to run task
[2025-03-26T13:38:24.923+0000] {task_command.py:467} INFO - Running <TaskInstance: containers1_dag.php_app2 scheduled__2024-03-07T00:00:00+00:00 [running]> on host 3d581a580455
[2025-03-26T13:38:25.789+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andre' AIRFLOW_CTX_DAG_ID='containers1_dag' AIRFLOW_CTX_TASK_ID='php_app2' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2025-03-26T13:38:25.791+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T13:38:26.130+0000] {docker.py:345} INFO - Starting docker container from image php-app2
[2025-03-26T13:38:26.198+0000] {docker.py:353} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-03-26T13:38:30.682+0000] {docker.py:69} INFO - array(19) {
[2025-03-26T13:38:30.683+0000] {docker.py:69} INFO -   [0]=>
[2025-03-26T13:38:30.684+0000] {docker.py:69} INFO -   object(stdClass)#2 (3) {
[2025-03-26T13:38:30.685+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.686+0000] {docker.py:69} INFO -     int(0)
[2025-03-26T13:38:30.686+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.687+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.687+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.687+0000] {docker.py:69} INFO -     int(1742852307)
[2025-03-26T13:38:30.688+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.689+0000] {docker.py:69} INFO -   [1]=>
[2025-03-26T13:38:30.690+0000] {docker.py:69} INFO -   object(stdClass)#3 (3) {
[2025-03-26T13:38:30.690+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.690+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.691+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.691+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.691+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.692+0000] {docker.py:69} INFO -     int(1742852309)
[2025-03-26T13:38:30.692+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.693+0000] {docker.py:69} INFO -   [2]=>
[2025-03-26T13:38:30.693+0000] {docker.py:69} INFO -   object(stdClass)#4 (3) {
[2025-03-26T13:38:30.694+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.694+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.694+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.695+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.695+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.696+0000] {docker.py:69} INFO -     int(1742852311)
[2025-03-26T13:38:30.696+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.696+0000] {docker.py:69} INFO -   [3]=>
[2025-03-26T13:38:30.697+0000] {docker.py:69} INFO -   object(stdClass)#5 (3) {
[2025-03-26T13:38:30.698+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.698+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.699+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.699+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.701+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.701+0000] {docker.py:69} INFO -     int(1742852314)
[2025-03-26T13:38:30.702+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.702+0000] {docker.py:69} INFO -   [4]=>
[2025-03-26T13:38:30.703+0000] {docker.py:69} INFO -   object(stdClass)#6 (3) {
[2025-03-26T13:38:30.704+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.705+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.705+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.705+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.706+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.706+0000] {docker.py:69} INFO -     int(1742996301)
[2025-03-26T13:38:30.707+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.707+0000] {docker.py:69} INFO -   [5]=>
[2025-03-26T13:38:30.707+0000] {docker.py:69} INFO -   object(stdClass)#7 (3) {
[2025-03-26T13:38:30.708+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.708+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.709+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.709+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.709+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.710+0000] {docker.py:69} INFO -     int(1742996302)
[2025-03-26T13:38:30.711+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.712+0000] {docker.py:69} INFO -   [6]=>
[2025-03-26T13:38:30.712+0000] {docker.py:69} INFO -   object(stdClass)#8 (3) {
[2025-03-26T13:38:30.712+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.713+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.713+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.713+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.714+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.714+0000] {docker.py:69} INFO -     int(1742996302)
[2025-03-26T13:38:30.714+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.715+0000] {docker.py:69} INFO -   [7]=>
[2025-03-26T13:38:30.715+0000] {docker.py:69} INFO -   object(stdClass)#9 (3) {
[2025-03-26T13:38:30.715+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.716+0000] {docker.py:69} INFO - int(1)
[2025-03-26T13:38:30.716+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.717+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.717+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.718+0000] {docker.py:69} INFO -     int(1742996303)
[2025-03-26T13:38:30.718+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.719+0000] {docker.py:69} INFO -   [8]=>
[2025-03-26T13:38:30.719+0000] {docker.py:69} INFO -   object(stdClass)#10 (3) {
[2025-03-26T13:38:30.719+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.720+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.720+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.721+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.721+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.722+0000] {docker.py:69} INFO -     int(1742996304)
[2025-03-26T13:38:30.722+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.723+0000] {docker.py:69} INFO -   [9]=>
[2025-03-26T13:38:30.723+0000] {docker.py:69} INFO -   object(stdClass)#11 (3) {
[2025-03-26T13:38:30.724+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.724+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.725+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.725+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.725+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.726+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:30.727+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.728+0000] {docker.py:69} INFO -   [10]=>
[2025-03-26T13:38:30.729+0000] {docker.py:69} INFO -   object(stdClass)#12 (3) {
[2025-03-26T13:38:30.730+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.730+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.730+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.731+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.731+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.732+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:30.733+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.734+0000] {docker.py:69} INFO -   [11]=>
[2025-03-26T13:38:30.736+0000] {docker.py:69} INFO -   object(stdClass)#13 (3) {
[2025-03-26T13:38:30.738+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.742+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.743+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.744+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.746+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.747+0000] {docker.py:69} INFO -     int(1742996305)
[2025-03-26T13:38:30.749+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.750+0000] {docker.py:69} INFO -   [12]=>
[2025-03-26T13:38:30.751+0000] {docker.py:69} INFO -   object(stdClass)#14 (3) {
[2025-03-26T13:38:30.753+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.754+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.755+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.756+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.757+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.758+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:30.759+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.760+0000] {docker.py:69} INFO -   [13]=>
[2025-03-26T13:38:30.760+0000] {docker.py:69} INFO -   object(stdClass)#15 (3) {
[2025-03-26T13:38:30.761+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.761+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.762+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.762+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.762+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.763+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:30.763+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.764+0000] {docker.py:69} INFO -   [14]=>
[2025-03-26T13:38:30.764+0000] {docker.py:69} INFO -   object(stdClass)#16 (3) {
[2025-03-26T13:38:30.765+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.766+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.766+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.767+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.768+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.768+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:30.769+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.769+0000] {docker.py:69} INFO -   [15]=>
[2025-03-26T13:38:30.770+0000] {docker.py:69} INFO -   object(stdClass)#17 (3) {
[2025-03-26T13:38:30.770+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.771+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.771+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.771+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.772+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.772+0000] {docker.py:69} INFO -     int(1742996309)
[2025-03-26T13:38:30.773+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.773+0000] {docker.py:69} INFO -   [16]=>
[2025-03-26T13:38:30.773+0000] {docker.py:69} INFO -   object(stdClass)#18 (3) {
[2025-03-26T13:38:30.774+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.774+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.774+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.775+0000] {docker.py:69} INFO -     string(8) "php-app1"
[2025-03-26T13:38:30.775+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.775+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:30.776+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.776+0000] {docker.py:69} INFO -   [17]=>
[2025-03-26T13:38:30.777+0000] {docker.py:69} INFO -   object(stdClass)#19 (3) {
[2025-03-26T13:38:30.777+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.777+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.778+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.778+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.778+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.779+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:30.779+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.779+0000] {docker.py:69} INFO -   [18]=>
[2025-03-26T13:38:30.780+0000] {docker.py:69} INFO -   array(3) {
[2025-03-26T13:38:30.780+0000] {docker.py:69} INFO -     ["contador"]=>
[2025-03-26T13:38:30.781+0000] {docker.py:69} INFO -     int(1)
[2025-03-26T13:38:30.782+0000] {docker.py:69} INFO -     ["container"]=>
[2025-03-26T13:38:30.782+0000] {docker.py:69} INFO -     string(8) "php-app2"
[2025-03-26T13:38:30.783+0000] {docker.py:69} INFO -     ["timestamp"]=>
[2025-03-26T13:38:30.783+0000] {docker.py:69} INFO -     int(1742996310)
[2025-03-26T13:38:30.783+0000] {docker.py:69} INFO -   }
[2025-03-26T13:38:30.784+0000] {docker.py:69} INFO - }
[2025-03-26T13:38:33.030+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T13:38:33.031+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=containers1_dag, task_id=php_app2, run_id=scheduled__2024-03-07T00:00:00+00:00, execution_date=20240307T000000, start_date=20250326T133823, end_date=20250326T133833
[2025-03-26T13:38:33.484+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-26T13:38:33.548+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T13:38:33.583+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
